# Generated by Django 6.0.2 on 2026-02-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Status')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Network Status',
                'verbose_name_plural': 'Network Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Network Type')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Network Type',
                'verbose_name_plural': 'Network Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn_number', models.PositiveIntegerField(db_index=True, help_text='Autonomous System Number (e.g., 64512)', unique=True, verbose_name='ASN Number')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('registered_on', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('registered_to', models.CharField(blank=True, max_length=255, verbose_name='Registered To')),
                ('registrar', models.CharField(blank=True, help_text='e.g., RIPE NCC, ARIN, APNIC', max_length=100, verbose_name='Registrar')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('peers', models.ManyToManyField(blank=True, to='asn.asn', verbose_name='Peering Partners')),
                ('upstreams', models.ManyToManyField(blank=True, related_name='downstreams', to='asn.asn', verbose_name='Upstream Providers')),
                ('network_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asns', to='asn.networkstatus', verbose_name='Network Status')),
                ('network_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asns', to='asn.networktype', verbose_name='Network Type')),
            ],
            options={
                'verbose_name': 'ASN',
                'verbose_name_plural': 'ASNs',
                'ordering': ['asn_number'],
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField(db_index=True, help_text='Base IP address of the prefix (e.g., 46.167.128.0)', verbose_name='Network Address')),
                ('prefix_length', models.PositiveSmallIntegerField(help_text='CIDR prefix length (e.g., 19 for /19)', verbose_name='Prefix Length')),
                ('ip_version', models.PositiveSmallIntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')], db_index=True, default=4, verbose_name='IP Version')),
                ('description', models.TextField(blank=True, help_text='Purpose or description of this prefix', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='asn.asn', verbose_name='ASN')),
            ],
            options={
                'verbose_name': 'IP Prefix',
                'verbose_name_plural': 'IP Prefixes',
                'ordering': ['ip_version', 'network', 'prefix_length'],
            },
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['asn_number'], name='asn_asn_asn_num_1dc1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['slug'], name='asn_asn_slug_476b86_idx'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['network_type', 'network_status'], name='asn_asn_network_c1bb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='prefix',
            index=models.Index(fields=['network', 'prefix_length'], name='asn_prefix_network_7fe4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='prefix',
            index=models.Index(fields=['ip_version', 'network'], name='asn_prefix_ip_vers_54489f_idx'),
        ),
        migrations.AddIndex(
            model_name='prefix',
            index=models.Index(fields=['asn', 'ip_version'], name='asn_prefix_asn_id_31a910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prefix',
            unique_together={('network', 'prefix_length', 'asn')},
        ),
    ]
