# Generated by Django 6.0.2 on 2026-02-26 20:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asn", "0002_remove_asn_peers"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Node Name")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Click on the map to set the node location",
                        srid=4326,
                        verbose_name="Geographical Location",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "asn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="asn.asn",
                        verbose_name="ASN",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Node",
                "verbose_name_plural": "Network Nodes",
                "ordering": ["name"],
            },
        ),
    ]
