# Generated by Django 6.0.2 on 2026-02-26 22:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asn", "0003_networknode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Location Name"),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Click on the map to set the exact coordinates",
                        srid=4326,
                        verbose_name="Coordinates",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="networknode",
            name="location",
        ),
        migrations.AddField(
            model_name="networknode",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="asn.location",
                verbose_name="Location",
            ),
            preserve_default=False,
        ),
    ]
